### ISSUE TITLE
Ability to export metrics to file

### ISSUE THREAD

**Issue by kurczynski** [prometheus-community/smartctl_exporter#110]
I have a [Grafana agent](https://grafana.com/docs/agent/latest/) running on my system at home and I'd like to simply write `smartctl` metrics to file so that the agent can handle all the configuration with the [node_exporter_config](https://grafana.com/docs/agent/latest/configuration/integrations/node-exporter-config/) integration. This could be enabled using a command line option that sets the file to write out to. Happy to create a PR for this if it's something of interest.

**Comment by NiceGuyIT** [comment]
Hi @kurczynski, Can you elaborate on what you are trying to achieve? Are you wanting to read the metrics from a file rather than a web page, while leaving the `smartctl_exporter` running normally? If so, a FIFO (`man mkfifo`) might help. If you're trying to get the metrics into Grafana, why not query it directly? If you can't query `smartctl_exporter` directly, what problems are you running into?

**Comment by kurczynski** [comment]
Yes, that is correct. I'd like to read the metrics from file while `smartctl_exporter` is running just to keep it simple for my homelab.

Yeah a FIFO would be fine, where can I pipe the metrics from `smartctl_exporter`?

**Comment by kurczynski** [comment]
So I wasn't aware that you could have the Grafana Agent scrape metrics from an endpoint, I thought the Grafana server had to scrape the metrics from an endpoint. Knowing that makes this request much less useful.
